[tool.poetry]
name = "pythonproject1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
#wypełniij jak nędziesz piublikować na PyPI
[tool.poetry.dependencies]
python = "^3.10"
#inf dla dev nie dla ludzi
flask = "^2.2.2"
#doszło po locku
pytest = "^5.2"
#powyzsze powinno przeladowac srodowisko, dociągnąć dependencies, ale an razie tego nei robi zobaczy jak sie zachowa po ponownym wlaczeniu
tzdata = "^2022.6"
csvreader = "^0.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
#standard komunikacyjny